version: 0.0                # 1) 스펙 버전

Resources:                  # 2) 배포 대상 서비스 매핑
  - TargetService:          #   ⏤ 임의 식별자(키)
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION_ARN>"     # 교체할 Task Definition ARN
        LoadBalancerInfo:                         # Blue/Green 배포 시 필요
          ContainerName: homs-backend
          ContainerPort: 8088

#Hooks:                      # 3) (선택) 배포 라이프사이클 훅
#  BeforeInstall:            #   ⏤ 코드(또는 Task Set) 설치 직전
#    - location: scripts/prep.sh
#      timeout: 300
#  BeforeAllowTraffic:       #   ⏤ 새 Task Set 띄우고 헬스체크 전에
#    - location: scripts/check_health.sh
#      timeout: 120
#  AfterAllowTraffic:        #   ⏤ 트래픽 완전 전환 후
#    - location: scripts/smoke_test.sh
#      timeout: 180