server:
  port: ${SERVER_PORT}
management:
  health:
    mail:
      enabled: false
logging:
  config: classpath:log4j2-spring-prod.xml
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
springboot:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}