spring:
  application:
    name: elk-example
  profiles:
    include: mariadb
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_S3_REGION}
server:
  port: 8088
springdoc:
  swagger-ui:
    version: v1.0.0
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.beyond.homs
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
