spring:
  application:
    name: elk-example
springdoc:
  swagger-ui:
    version: v1.0.0
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.beyond.homs
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
excel:
  template:
    path: templates/excel_templates.xlsx